version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "reservation-ecs"
          ContainerPort: 80
        PlatformVersion: "LATEST"
DeploymentConfiguration:
  DeploymentStyle:
    DeploymentOption: WITH_TRAFFIC_CONTROL
    DeploymentType: BLUE_GREEN
  BlueGreenDeploymentConfiguration:
    DeploymentReadyOption:
      ActionOnTimeout: CONTINUE_DEPLOYMENT
      WaitTimeInMinutes: 0
    TerminateBlueInstancesOnDeploymentSuccess:
      Action: TERMINATE
      TerminationWaitTimeInMinutes: 5
