version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:339712923306:task-definition/cloudtech-reservation-api-task"
        LoadBalancerInfo:
          ContainerName: "reservation-ecs"
          ContainerPort: "80"
